### ISSUE TITLE
Different stubs are sharing arguments

### ISSUE THREAD

**Issue by jonathan-benn** [note35/sinon#3]
```
stub1 = sinon.stub()
stub2 = sinon.stub()
stub1(1, 2, 3)
stub2(4, 5, 6)
print stub2.getCall(0).args # [(1, 2, 3)]
print stub2.args # [(4, 5, 6)]
```

The call to `stub2.getCall(0).args` should return `(4, 5, 6)`. Somehow this call is returning the arguments from `stub1`!

**Comment by note35** [comment]
Please reference the comment of current design [HERE](https://github.com/note35/sinon/issues/2#issuecomment-331641685) first.

This issue's root cause is because the design of `args_list` and `_queue` are two separated concepts. stub2.getCall(0) in current design will get the first call of all Spies/Stubs. I believe that to fix this, we need to redesign some structure behind base. (Maybe move it to spy/wrapper)

I currently might not be able to fix it quickly. Feel free to dig this issue deeply. :)
